name: device_preview
version: 1.2.0
publish_to: none
description: Approximate how your Flutter app looks and performs on another device.
homepage: https://github.com/aloisdeniel/flutter_device_preview

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=3.22.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  device_frame:
    git: https://github.com/sumitsharansatsangi/device_frame.git
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
 # freezed: ^2.5.3
  json_serializable: ^6.8.0
